#!/bin/sh
xhost +
if ! [ -d $HOME/Jagex ]; then
	mkdir -p $HOME/Jagex
fi

if ! [ -d $HOME/.runescape ]; then
	mkdir -p $HOME/.runescape
fi

docker run --rm \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e DISPLAY=$DISPLAY \
  -v ${HOME}/.runescape:/home/runescape/.runescape \
  -v ${HOME}/Jagex:/home/runescape/Jagex \
fusion809/runescape-launcher /usr/bin/runescape-launcher
